### ISSUE TITLE
"index out of bounds" panic when last token cannot be parsed

### ISSUE THREAD

**Issue by dwrensha** [shepmaster/fuzzy-pickles#53]
```
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
$ echo ح > input
$ xxd input
00000000: d8ad 0a                                  ...
$ RUST_BACKTRACE=1 ./target/debug/stats input 
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /checkout/src/libcollections/vec.rs:1426
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <collections::vec::Vec<T> as core::ops::Index<usize>>::index
             at /checkout/src/libcollections/vec.rs:1426
   1: fuzzy_pickles::parse_rust_file
             at ./src/lib.rs:309
   2: stats::main
             at ./src/bin/stats.rs:28
```

This out-of-bounds panic seems to have been introduced in https://github.com/shepmaster/fuzzy-pickles/pull/45; before that change, the error message was the following, which is less worrysome:
```
thread 'main' panicked at 'Unable to parse input
Unable to parse text (line 2, column 1)


^
Expected:
  Literal("\t")
  Literal("\r")
  Literal(" ")
  Literal("!")
  Literal("/*")
  Literal("//")
', src/bin/stats.rs:31
```

**Comment by dwrensha** [comment]
(found with the help of [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz)))

**Comment by shepmaster** [comment]
At least it's not actually a Unicode issue ;-)

```
$ echo a > one.rs
$ ./target/debug/stats one.rs
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/libcollections/vec.rs:1484
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by shepmaster** [comment]
Something like this too

``rust
fn main() {

}

a
```

**Comment by shepmaster** [comment]
A local fix I have corrects the issue:

```
thread 'main' panicked at 'Unable to parse one.rs
Unable to parse text (line 5, column 2)

a
 ^
Expected:
  ExpectedBang
```

**Comment by shepmaster** [comment]
Which also showed me that evidently the real compiler can have pathed macros, as it says it's expecting a `::` or `!`. Strange.
